
server:
  port: 6380
spring:
  application:
    name: camellia-redis-proxy-server

camellia-redis-proxy:
  password: pass123
  transpond:
    type: local
    local:
      resource: redis://@127.0.0.1:6379
    redis-conf:
      queue-type: linkedblockingqueue

#camellia-redis-zk-registry:
#  enable: false
#  zk-url: 127.0.0.1:2181
#  base-path: /camellia
