
server:
  port: 6381
spring:
  application:
    name: camellia-redis-proxy-server

camellia-redis-proxy:
#  password: pass123
  transpond:
    type: local
    local:
      resource: redis://@127.0.0.1:6379
  monitor-enable: true
  command-spend-time-monitor-enable: true
  monitor-interval-seconds: 10
#  command-filter-class-name: com.netease.nim.camellia.redis.proxy.command.async.DummyCommandFilter

