
server:
  port: 6381
spring:
  application:
    name: camellia-redis-proxy-hbase

#see CamelliaRedisProxyProperties
camellia-redis-proxy:
  console-port: 16379
#  password: xxxx
  monitor-enable: false
  monitor-interval-seconds: 60
  upstream-client-template-chooser-class-name: com.netease.nim.camellia.redis.proxy.hbase.UpstreamRedisHBaseMixClientTemplateChooser
  plugins: #plugin list
    - monitorPlugin
    - bigKeyPlugin
    - hotKeyPlugin
  #  config: #you can get this config from ProxyDynamicConf.java, priority less than camellia-redis-proxy.properties
  #    "k": v
  transpond: ## transpond conf is noneffective for upstream-client-template-chooser-class-name is rewrite
    type: local #local、remote、custom
    local:
      type: simple #simple、complex
      resource: redis://@127.0.0.1:6379 #target transpond redis address

#see CamelliaHBaseProperties
camellia-hbase:
  type: local
  local:
    xml:
      xml-file: hbase.xml

#see CamelliaRedisProperties
camellia-redis:
  type: local
  local:
    resource: redis://abc@127.0.0.1:6379
