
server:
  port: 6381
spring:
  application:
    name: camellia-redis-proxy-server

#see CamelliaRedisProxyProperties
camellia-redis-proxy:
  password: pass123
  console-port: 16379

#see CamelliaHBaseProperties
camellia-hbase:
  type: local
  local:
    xml:
      xml-file: hbase.xml

#see CamelliaRedisProperties
camellia-redis:
  type: local
  local:
    resource: redis://abc@127.0.0.1:6379
